version: '3.8'
services:
  web:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db-teste.c4jsgssi0pnf.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin1234
      WORDPRESS_DB_NAME: db-teste
    networks:
      - tunel
networks:
  tunel:
    driver: bridge


