version: '3.8'
services:
  web:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: <HOST DO BD>
      WORDPRESS_DB_USER: < ADMIN >
      WORDPRESS_DB_PASSWORD: <SENHA>
      WORDPRESS_DB_NAME: < NOME DO BD> 
    volumes:
      - /mnt/efs/wp-content:/var/www/html/wp-content
    networks:
      - tunel
networks:
  tunel:
    driver: bridge
