version: '3.8'
services:
  web:
    image: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: bd-wordpress.c4jsgssi0pnf.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 10203040
      WORDPRESS_DB_NAME: bd_wordpress
    volumes:
      - /mnt/efs/wp-content:/var/www/html/wp-content
    networks:
      - tunel
networks:
  tunel:
    driver: bridge
